### PR TITLE
fix(deprecation): disuse deprecated React functional component defaultProps feature

### LINKED ISSUE #450: Warning: Connect(Droppable): Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead.
https://github.com/hello-pangea/dnd/blob/02daac951338d40127bc2e1b989b9116a989debc/src/view/droppable/connected-droppable.ts#L277

image

### PR DESCRIPTION
**Pull request by klarstrup**
In the next major React version, `defaultProps` will only be supported on class components. `react-redux`'s `connect` returns a functional component which will not support this in that future.

see https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md and https://github.com/facebook/react/pull/16210

fixes #450

### CODE REVIEW

**Comment by xiaotianxt** [comment]
I managed to fix this by using `pnpm@8.1.1` #544

**Comment by joao-vasconcelos** [comment]
Hello, any update on this?
Thank you for keeping this package working <3

**Comment by namnhfreelancer** [comment]
Any update about merging it ?

**Comment by 100terres** [comment]
We made the required change in [this PR](https://github.com/hello-pangea/dnd/pull/579) and it will be part of the next release! :blush: 

Thank you for your contribution!

**Pull request closed without merging**
