### PR TITLE
refactor(types): make `Id` generic

### LINKED ISSUE #817: Add Generics to `DropResult` type
### Description

Making `DropResult` a generic type to specify type of `droppableId`

Right now I have to assert the type.

```ts
  async function onDragEng({ source, destination, draggableId }: DropResult) {
    if (!destination) return

    if (destination.droppableId === source.droppableId) {
      reorderTasks(
        source.droppableId as BoardKey,
        source.index,
        destination.index
      )
    }
  }
  ```
  
  I would like to specify type for `droppableId` in DropResult type argument
  
  ```ts
  async function onDragEng({ source, destination, draggableId }: DropResult<BoardKey>) {
    if (!destination) return

    if (destination.droppableId === source.droppableId) {
      reorderTasks(
        source.droppableId,
        source.index,
        destination.index
      )
    }
  }
  ```

### PR DESCRIPTION
**Pull request by Mnigos**
Id should have type argument that accepts string literals

closes #817

### CODE REVIEW

**Review by 100terres — APPROVED** [review]
Thank you for this :ok_hand:

**Comment by Prains** [comment]
omg just came here looking if library has a maintainer and he closes pr immediately

**Comment by 100terres** [comment]
@Mnigos your changes are included in the v17.0.0. Thank you again.

**Comment by Mnigos** [comment]
> @Mnigos your changes are included in the v17.0.0. Thank you again.

That's great to hear!

**Pull request merged**
